version: "3.8"
services:
  deliberation-empirica: 
    platform: linux/amd64  # needed when developing on apple silicon, harmless otherwise
    build: .
    ports:
      - 3000:3000  # empirica
    volumes:
      # need to be careful about overwriting `/node_modules` in container
      # hack from https://burnedikt.com/dockerized-node-development-and-mounting-node-volumes/#exclude-node_modules-from-the-mount  
      - ./.meteor:/app/.meteor
      - ./client:/app/client
      - ./public:/app/public
      - ./server:/app/server
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    entrypoint:
      - "meteor"
      - "--allow-superuser"


  deliberation-storybook:
    platform: linux/amd64
    build: .
    ports:
      - 6006:6006  # storybook
    volumes:
      - ./.storybook:/app/.storybook
      - ./client:/app/client
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    entrypoint: 
      - "npm"
      - "run"
      - "storybook"
      # - "--no-manager-cache" # uncomment if you see "Cannot GET /" in the storybook browser
      
